# Generated by Django 5.0.6 on 2024-06-25 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('name', 'website')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('shop', models.CharField(max_length=255, null=True)),
                ('last_changes', models.DateTimeField(auto_now=True, null=True)),
                ('last_changes_details', models.TextField(blank=True, null=True)),
                ('category_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='scrapper.category')),
            ],
        ),
    ]
