# Generated by Django 5.0.6 on 2024-06-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
